services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    env_file: env/database.env
    networks:
      - postgres

  customers:
    build:
      context: ./customers
    container_name: customers
    ports:
      - 3001:3000
    networks:
      - rabbitmq
      - postgres

  orders:
    build:
      context: ./orders
    container_name: orders
    ports:
      - 3002:3000
    networks:
      - rabbitmq
      - postgres

  products:
    build:
      context: ./products
    container_name: products
    ports:
      - 3003:3000
    networks:
      - rabbitmq
      - postgres

networks:
  rabbitmq:
    driver: bridge
  postgres: