services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    env_file: env/database.env

  customers:
    build:
      context: ./customers

  orders:
    build:
      context: ./orders

  products:
    build:
      context: ./products

networks:
  rabbitmq:
    driver: bridge
