#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_PRODUCTS_USER WITH PASSWORD '$POSTGRES_CUSTOMERS_PASSWORD';
	CREATE DATABASE $POSTGRES_PRODUCTS_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_PRODUCTS_DB TO $POSTGRES_CUSTOMERS_USER;
EOSQL
